# -*- coding: utf-8 -*-
"""OASIS INFOBYTE TASK4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MrCCf0R9XSg1h3twx101dPAt0tnFei0U
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import statsmodels
from statsmodels.stats.anova import anova_lm
from statsmodels.stats.outliers_influence import variance_inflation_factor
import seaborn as sns
from matplotlib import pyplot as plt
# %matplotlib inline

df = pd.read_csv(r"/content/car data.csv")
df

"""Data Pre-Processing"""

df.info()

# count the number of NaN values in each column
df.isnull().sum()

sns.boxplot(data = df)

"""Descriptive Analysis"""

df.describe()

sns.pairplot(data = df)

"""Breaking Dataset into 2 Parts"""

# Quantitative Variable (Numbers)
Quantitative_Variable = df[df.select_dtypes(include=[np.number]).columns.tolist()]
Quantitative_Variable.head(3)

# Qualitative Variable (Objects)
Qualitative_Variable = df[df.select_dtypes(include=['object']).columns.tolist()]
Qualitative_Variable.head(3)

from sklearn.preprocessing import LabelEncoder
Qualitative_Variable=Qualitative_Variable.apply(LabelEncoder().fit_transform) # label in ascending order
Qualitative_Variable.head()

Final_combined = pd.concat([Qualitative_Variable, Quantitative_Variable],axis=1)
Final_combined.head()