# -*- coding: utf-8 -*-
"""OASIS INFOBYTE TASK2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qTJNCh9dNVoQPNyQ1frwZHLFjsyA5GfW

Import Libraries
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
import calendar
import plotly.graph_objects as go

import warnings
warnings.filterwarnings("ignore")
# %matplotlib inline

"""Load And Explore The Dataset"""

data = pd.read_csv("/content/Unemployment in India.csv")
data

data.shape

data.columns

data.describe()

data.isnull().sum()

data.duplicated().any()

data.State.value_counts()

"""Exploratory Data Analysis"""

#Basic Statistics
data_stats = data[['Estimated unemployment rate', 'Estimated employed', 'Estimated labour participation rate']]
round(data_stats.describe().T, 2)

region_stats = data.groupby(['Region'])[['Estimated unemployment rate', 'Estimated employed',
                                       'Estimated labour participation rate']].mean().reset_index()
round(region_stats, 2)

"""Data Visualization"""

# Make sure the 'Month' column exists in your DataFrame.
# If it's not present, you might need to extract it from the 'Date' column.
# Assuming 'Date' is in the format 'YYYY-MM-DD', you can extract the month as follows:

data['Month'] = pd.to_datetime(data['Date']).dt.strftime('%b') # Extract month abbreviations

IMD = data.groupby(["Month"])[['Estimated unemployment rate','Estimated employed','Estimated labour participation rate']].mean()
IMD = pd.DataFrame(IMD).reset_index()
month = IMD.Month
unemployment_rate = IMD["Estimated unemployment rate"]
labour_participation_rate = IMD["Estimated labour participation rate"]
month = IMD.Month
unemployment_rate = IMD["Estimated unemployment rate"]
labour_participation_rate = IMD["Estimated labour participation rate"]

fig = go.Figure()

fig.add_trace(go.Bar(x=month, y= unemployment_rate, name = "Unemployment Rate"))
fig.add_trace(go.Bar(x= month , y = labour_participation_rate, name = "Labourparticipation Rate"))

fig.update_layout(title = "Unemploymnet Rate and Labour Participation rate ",
                 xaxis= {"categoryorder":"array","categoryarray":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct"]})

fig.show()

# ... (rest of your code)

"""Average Unemployment rate bar plot"""

import plotly.express as px

# Assuming 'data' is your DataFrame containing state-wise unemployment data
State = data.groupby('State')['Estimated unemployment rate'].mean().reset_index()

fig = px.bar(State, x='State', y='Estimated unemployment rate', color="State",title="Average Unemployment Rate (State)")
fig.update_layout(xaxis={'categoryorder':'total descending'})

fig.show()

"""# Animated bar plot of Unemployment rate across region"""

import plotly.express as px

# Assuming 'data' is your DataFrame containing state-wise unemployment data
# and it has a column named 'Month'
fig = px.bar(data, x='Region', y='Estimated unemployment rate', animation_frame='Month', color='State',
             title='Unemployment rate across region from Jan.2020 to Oct.2020', height=700, template='plotly')
fig.update_layout(xaxis={'categoryorder': 'total descending'})
fig.layout.updatemenus[0].buttons[0].args[1]["frame"]["duration"] = 2000
fig.show()

"""Scatter Matrix"""

fig = px.scatter_matrix(data, template='plotly',
                        dimensions=['Estimated unemployment rate', 'Estimated employed', 'Estimated labour participation rate'],
                        color='Region')
fig.show()

"""Sunburst chart"""

# Sunburst chart showing unemployment rate in each region and state

unemplo_df = data[['State', 'Region', 'Estimated unemployment rate', 'Estimated employed', 'Estimated labour participation rate']]
unemplo = unemplo_df.groupby(['Region', 'State'])['Estimated unemployment rate'].mean().reset_index()
fig = px.sunburst(unemplo, path=['Region', 'State'], values='Estimated unemployment rate',
                  color_continuous_scale='Plasma', title='Unemployment rate in each region and state',
                  height=650, template='ggplot2')
fig.show()